import { CarouselProjectImg } from '../../types/projects';

export const DataCarousel2DBack: CarouselProjectImg[] = [
  {
    imageName: 'back1.webp',
    description: 'back1',
    general: false,
    src: 'assoFacTory/back1.webp',
    alt: 'AssoFacTory back',
    projectName: 'assoFacTory',
  },
  {
    imageName: 'back2.webp',
    description: 'back2',
    general: false,
    src: 'assoFacTory/back2.webp',
    alt: 'AssoFacTory back',
    projectName: 'assoFacTory',
  },
  {
    imageName: 'back3.webp',
    description: 'back3',
    general: false,
    src: 'assoFacTory/back3.webp',
    alt: 'AssoFacTory back',
    projectName: 'assoFacTory',
  },
  {
    imageName: 'back4.webp',
    description: 'back4',
    general: false,
    src: 'assoFacTory/back4.webp',
    alt: 'AssoFacTory back',
    projectName: 'assoFacTory',
  },
  {
    imageName: 'back5.webp',
    description: 'back5',
    general: false,
    src: 'assoFacTory/back5.webp',
    alt: 'AssoFacTory back',
    projectName: 'assoFacTory',
  },
  {
    imageName: 'back6.webp',
    description: 'back6',
    general: false,
    src: 'assoFacTory/back6.webp',
    alt: 'AssoFacTory back',
    projectName: 'assoFacTory',
  },
  {
    imageName: 'back7.webp',
    description: 'back7',
    general: false,
    src: 'assoFacTory/back7.webp',
    alt: 'AssoFacTory back',
    projectName: 'assoFacTory',
  },
  {
    imageName: 'back8.webp',
    description: 'back8',
    general: false,
    src: 'assoFacTory/back8.webp',
    alt: 'AssoFacTory back',
    projectName: 'assoFacTory',
  },
  {
    imageName: 'back9.webp',
    description: 'back9',
    general: false,
    src: 'assoFacTory/back9.webp',
    alt: 'AssoFacTory back',
    projectName: 'assoFacTory',
  },
  {
    imageName: 'back10.webp',
    description: 'back10',
    general: false,
    src: 'assoFacTory/back10.webp',
    alt: 'AssoFacTory back',
    projectName: 'assoFacTory',
  },
  {
    imageName: 'back11.webp',
    description: 'back11',
    general: false,
    src: 'assoFacTory/back11.webp',
    alt: 'AssoFacTory back',
    projectName: 'assoFacTory',
  },

  {
    imageName: 'back1.webp',
    description: 'test',
    general: false,
    src: 'connectify/back1.webp',
    alt: 'Connectify back',
    projectName: 'Connectify',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: 'connectify/back2.webp',
    alt: 'Connectify back',
    projectName: 'Connectify',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: 'connectify/back3.webp',
    alt: 'Connectify back',
    projectName: 'Connectify',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: 'connectify/back4.webp',
    alt: 'Connectify back',
    projectName: 'Connectify',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: 'connectify/back5.webp',
    alt: 'Connectify back',
    projectName: 'Connectify',
  },
  {
    imageName: 'back6.webp',
    description: 'test',
    general: false,
    src: 'connectify/back6.webp',
    alt: 'Connectify back',
    projectName: 'Connectify',
  },
  {
    imageName: 'back7.webp',
    description: 'test',
    general: false,
    src: 'connectify/back7.webp',
    alt: 'Connectify back',
    projectName: 'Connectify',
  },
  {
    imageName: 'back8.webp',
    description: 'test',
    general: false,
    src: 'connectify/back8.webp',
    alt: 'Connectify back',
    projectName: 'Connectify',
  },
  {
    imageName: 'back9.webp',
    description: 'test',
    general: false,
    src: 'connectify/back9.webp',
    alt: 'Connectify back',
    projectName: 'Connectify',
  },
  {
    imageName: 'back10.webp',
    description: 'test',
    general: false,
    src: 'connectify/back10.webp',
    alt: 'Connectify back',
    projectName: 'Connectify',
  },
  {
    imageName: 'back11.webp',
    description: 'test',
    general: false,
    src: 'connectify/back11.webp',
    alt: 'Connectify back',
    projectName: 'Connectify',
  },

  {
    imageName: 'back1.webp',
    description: 'test',
    general: false,
    src: 'garage/back1.webp',
    alt: 'Garage back',
    projectName: 'Garage',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: 'garage/back2.webp',
    alt: 'Garage back',
    projectName: 'Garage',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: 'garage/back3.webp',
    alt: 'Garage back',
    projectName: 'Garage',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: 'garage/back4.webp',
    alt: 'Garage back',
    projectName: 'Garage',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: 'garage/back5.webp',
    alt: 'Garage back',
    projectName: 'Garage',
  },
  {
    imageName: 'back6.webp',
    description: 'test',
    general: false,
    src: 'garage/back6.webp',
    alt: 'Garage back',
    projectName: 'Garage',
  },
  {
    imageName: 'back7.webp',
    description: 'test',
    general: false,
    src: 'garage/back7.webp',
    alt: 'Garage back',
    projectName: 'Garage',
  },

  {
    imageName: 'back1.webp',
    description: 'test',
    general: false,
    src: 'seaLife/back1.webp',
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: 'seaLife/back2.webp',
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: 'seaLife/back3.webp',
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: 'seaLife/back4.webp',
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: 'seaLife/back5.webp',
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back6.webp',
    description: 'test',
    general: false,
    src: 'seaLife/back6.webp',
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back7.webp',
    description: 'test',
    general: false,
    src: 'seaLife/back7.webp',
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back8.webp',
    description: 'test',
    general: false,
    src: 'seaLife/back8.webp',
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back9.webp',
    description: 'test',
    general: false,
    src: 'seaLife/back9.webp',
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  //////
  {
    imageName: 'back1.webp',
    description: '',
    general: false,
    src: 'teamChallenge/back1.webp',
    alt: 'main page',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'back2.webp',
    description: '',
    general: false,
    src: 'teamChallenge/back2.webp',
    alt: 'main page 2 screen',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'back3.webp',
    description: '',
    general: false,
    src: 'teamChallenge/back3.webp',
    alt: 'main page 3 screen',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'back4.webp',
    description: '',
    general: false,
    src: 'teamChallenge/back4.webp',
    alt: 'user account',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'back5.webp',
    description: '',
    general: false,
    src: 'teamChallenge/back5.webp',
    alt: 'page my progects',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'back6.webp',
    description: '',
    general: false,
    src: 'teamChallenge/back6.webp',
    alt: 'teams',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'back7.webp',
    description: '',
    general: false,
    src: 'teamChallenge/back7.webp',
    alt: 'mobile',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'back8.webp',
    description: '',
    general: false,
    src: 'teamChallenge/back8.webp',
    alt: 'mobile',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'back9.webp',
    description: '',
    general: false,
    src: 'teamChallenge/back9.webp',
    alt: 'join',
    projectName: 'teamChallenge',
  },

  {
    imageName: 'back1.webp',
    description: 'test',
    general: false,
    src: 'diamondCollection/back1.webp',
    alt: 'diamondCollection back',
    projectName: 'diamondCollection',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: 'diamondCollection/back2.webp',
    alt: 'diamondCollection back',
    projectName: 'diamondCollection',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: 'diamondCollection/back3.webp',
    alt: 'diamondCollection back',
    projectName: 'diamondCollection',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: 'diamondCollection/back4.webp',
    alt: 'diamondCollection back',
    projectName: 'diamondCollection',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: 'diamondCollection/back5.webp',
    alt: 'diamondCollection back',
    projectName: 'diamondCollection',
  },
  {
    imageName: 'back6.webp',
    description: 'test',
    general: false,
    src: 'diamondCollection/back6.webp',
    alt: 'diamondCollection back',
    projectName: 'diamondCollection',
  },
  {
    imageName: 'back7.webp',
    description: 'test',
    general: false,
    src: 'diamondCollection/back7.webp',
    alt: 'diamondCollection back',
    projectName: 'diamondCollection',
  },

  {
    imageName: 'back1.webp',
    description: 'back1',
    general: false,
    src: 'ABS/back1.webp',
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: 'ABS/back2.webp',
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: 'ABS/back3.webp',
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: 'ABS/back4.webp',
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: 'ABS/back5.webp',
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back6.webp',
    description: 'test',
    general: false,
    src: 'ABS/back6.webp',
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back7.webp',
    description: 'test',
    general: false,
    src: 'ABS/back7.webp',
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back8.webp',
    description: 'test',
    general: false,
    src: 'ABS/back8.webp',
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back9.webp',
    description: 'test',
    general: false,
    src: 'ABS/back9.webp',
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back10.webp',
    description: 'test',
    general: false,
    src: 'ABS/back10.webp',
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back11.webp',
    description: 'test',
    general: false,
    src: 'ABS/back11.webp',
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back12.webp',
    description: 'test',
    general: false,
    src: 'ABS/back12.webp',
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back13.webp',
    description: 'test',
    general: false,
    src: 'ABS/back13.webp',
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back14.webp',
    description: 'test',
    general: false,
    src: 'ABS/back14.webp',
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back15.webp',
    description: 'test',
    general: false,
    src: 'ABS/back15.webp',
    alt: 'ABS back',
    projectName: 'ABS',
  },

  {
    imageName: 'back1.webp',
    description: 'test',
    general: false,
    src: 'ekea/back1.webp',
    alt: 'ekea code',
    projectName: 'ekea',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: 'ekea/back2.webp',
    alt: 'ekea code',
    projectName: 'ekea',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: 'ekea/back3.webp',
    alt: 'ekea code',
    projectName: 'ekea',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: 'ekea/back4.webp',
    alt: 'ekea code',
    projectName: 'ekea',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: 'ekea/back5.webp',
    alt: 'ekea code',
    projectName: 'ekea',
  },
  {
    imageName: 'back6.webp',
    description: 'test',
    general: false,
    src: 'ekea/back6.webp',
    alt: 'ekea code',
    projectName: 'ekea',
  },
  {
    imageName: 'back7.webp',
    description: 'test',
    general: false,
    src: 'ekea/back7.webp',
    alt: 'ekea code',
    projectName: 'ekea',
  },
  {
    imageName: 'back8.webp',
    description: 'test',
    general: false,
    src: 'ekea/back8.webp',
    alt: 'ekea code',
    projectName: 'ekea',
  },

  {
    imageName: 'back1.webp',
    description: 'test',
    general: false,
    src: 'karamonVideo/back1.webp',
    alt: 'karamonVideo back',
    projectName: 'karamonVideo',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: 'karamonVideo/back2.webp',
    alt: 'karamonVideo back',
    projectName: 'karamonVideo',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: 'karamonVideo/back3.webp',
    alt: 'karamonVideo back',
    projectName: 'karamonVideo',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: 'karamonVideo/back4.webp',
    alt: 'karamonVideo back',
    projectName: 'karamonVideo',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: 'karamonVideo/back5.webp',
    alt: 'karamonVideo back',
    projectName: 'karamonVideo',
  },
  {
    imageName: 'back6.webp',
    description: 'test',
    general: false,
    src: 'karamonVideo/back6.webp',
    alt: 'karamonVideo back',
    projectName: 'karamonVideo',
  },

  {
    imageName: 'back1.webp',
    description: 'test',
    general: false,
    src: 'nastyaPhoto/back1.webp',
    alt: 'nastyaPhoto back',
    projectName: 'nastyaPhoto',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: 'nastyaPhoto/back2.webp',
    alt: 'nastyaPhoto back',
    projectName: 'nastyaPhoto',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: 'nastyaPhoto/back3.webp',
    alt: 'nastyaPhoto back',
    projectName: 'nastyaPhoto',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: 'nastyaPhoto/back4.webp',
    alt: 'nastyaPhoto back',
    projectName: 'nastyaPhoto',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: 'nastyaPhoto/back5.webp',
    alt: 'nastyaPhoto back',
    projectName: 'nastyaPhoto',
  },
  {
    imageName: 'back6.webp',
    description: 'test',
    general: false,
    src: 'nastyaPhoto/back6.webp',
    alt: 'nastyaPhoto back',
    projectName: 'nastyaPhoto',
  },

  {
    imageName: 'back1.webp',
    description: 'test',
    general: false,
    src: 'weatherReact/back1.webp',
    alt: 'weatherReact back',
    projectName: 'weatherReact',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: 'weatherReact/back2.webp',
    alt: 'weatherReact back',
    projectName: 'weatherReact',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: 'weatherReact/back3.webp',
    alt: 'weatherReact back',
    projectName: 'weatherReact',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: 'weatherReact/back4.webp',
    alt: 'weatherReact back',
    projectName: 'weatherReact',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: 'weatherReact/back5.webp',
    alt: 'weatherReact back',
    projectName: 'weatherReact',
  },

  {
    imageName: 'back1.webp',
    description: 'test',
    general: false,
    src: 'casinoGame/back1.webp',
    alt: 'casinoGame back',
    projectName: 'casinoGame',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: 'casinoGame/back2.webp',
    alt: 'casinoGame back',
    projectName: 'casinoGame',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: 'casinoGame/back3.webp',
    alt: 'casinoGame back',
    projectName: 'casinoGame',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: 'casinoGame/back4.webp',
    alt: 'casinoGame back',
    projectName: 'casinoGame',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: 'casinoGame/back5.webp',
    alt: 'casinoGame back',
    projectName: 'casinoGame',
  },

  {
    imageName: 'back1.webp',
    description: 'test',
    general: false,
    src: 'portfolio/back1.webp',
    alt: 'portfolio back',
    projectName: 'portfolio',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: 'portfolio/back2.webp',
    alt: 'portfolio back',
    projectName: 'portfolio',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: 'portfolio/back3.webp',
    alt: 'portfolio back',
    projectName: 'portfolio',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: 'portfolio/back4.webp',
    alt: 'portfolio back',
    projectName: 'portfolio',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: 'portfolio/back5.webp',
    alt: 'portfolio back',
    projectName: 'portfolio',
  },
  {
    imageName: 'back6.webp',
    description: 'test',
    general: false,
    src: 'portfolio/back6.webp',
    alt: 'portfolio back',
    projectName: 'portfolio',
  },
  {
    imageName: 'back7.webp',
    description: 'test',
    general: false,
    src: 'portfolio/back7.webp',
    alt: 'portfolio back',
    projectName: 'portfolio',
  },
];
