import { CarouselProjectImg } from '../../types/projects';

/**
 * Builds carousel entries for a project from the screenshot count.
 * Images live at src/images/MyProjects/Front/<projectName>/front1.webp ... frontN.webp
 * description stays empty — the carousel hides the caption when it is empty
 * (see carousel.tsx). Captions are set explicitly per slide, like teamChallenge.
 */
const project = (
  projectName: string,
  count: number,
  alt: string,
): CarouselProjectImg[] =>
  Array.from({ length: count }, (_, i) => {
    const n = i + 1;
    return {
      imageName: `front${n}.webp`,
      description: '',
      general: false,
      src: require(`../../images/MyProjects/Front/${projectName}/front${n}.webp`),
      alt,
      projectName,
    };
  });

// teamChallenge is the only project with meaningful captions
// (slides.teamChallenge.* keys in translations.json), so it is defined explicitly.
const teamChallenge: CarouselProjectImg[] = [
  {
    imageName: 'front1.webp',
    description: 'slides.teamChallenge.main_hero',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front1.webp'),
    alt: 'Main page hero with role grid',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front2.webp',
    description: 'slides.teamChallenge.main_screen2',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front2.webp'),
    alt: 'Create own project card + steps explainer',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front3.webp',
    description: 'slides.teamChallenge.main_screen3',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front3.webp'),
    alt: 'Choose your project buttons',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front4.webp',
    description: 'slides.teamChallenge.main_modal',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front4.webp'),
    alt: 'Project description modal',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front5.webp',
    description: 'slides.teamChallenge.my_projects',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front5.webp'),
    alt: 'My Projects page — table and mobile cards',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front6.webp',
    description: 'slides.teamChallenge.footer_privacy',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front6.webp'),
    alt: 'Footer and privacy policy page',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front7.webp',
    description: 'slides.teamChallenge.menu_config',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front7.webp'),
    alt: 'Config-driven menu items',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front8.webp',
    description: 'slides.teamChallenge.menu_lazy',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front8.webp'),
    alt: 'Lazy drawer status fetching',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front9.webp',
    description: 'slides.teamChallenge.ui_styled',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front9.webp'),
    alt: 'Styled components with theme tokens',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front10.webp',
    description: 'slides.teamChallenge.ui_mobile',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front10.webp'),
    alt: 'Dedicated mobile components',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front11.webp',
    description: 'slides.teamChallenge.ui_i18n',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front11.webp'),
    alt: 'i18n from day one',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front12.webp',
    description: 'slides.teamChallenge.auth_guard',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front12.webp'),
    alt: 'withAuthGuard HOC + redirect loops',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front13.webp',
    description: 'slides.teamChallenge.auth_refresh',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front13.webp'),
    alt: 'Auth0 refresh tokens + invalid_grant',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front14.webp',
    description: 'slides.teamChallenge.auth_public',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front14.webp'),
    alt: 'Public route awareness',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front15.webp',
    description: 'slides.teamChallenge.rq_factory',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front15.webp'),
    alt: 'createUseQuery factory',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front16.webp',
    description: 'slides.teamChallenge.rq_userstatus',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front16.webp'),
    alt: 'useUserStatus domain hook',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front17.webp',
    description: 'slides.teamChallenge.rq_gating',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front17.webp'),
    alt: 'Query gating with enabled flag',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front18.webp',
    description: 'slides.teamChallenge.team_stepper',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front18.webp'),
    alt: 'Join flow stepper state machine',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front19.webp',
    description: 'slides.teamChallenge.team_decisions',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front19.webp'),
    alt: 'Vacancies UI with decision statuses',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front20.webp',
    description: 'slides.teamChallenge.team_pagination',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front20.webp'),
    alt: 'Backend pagination with getPage util',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front21.webp',
    description: 'slides.teamChallenge.stripe_di',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front21.webp'),
    alt: 'Stripe service architecture with DI',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front22.webp',
    description: 'slides.teamChallenge.stripe_transformer',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front22.webp'),
    alt: 'Stripe transformer layer',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front23.webp',
    description: 'slides.teamChallenge.stripe_reconcile',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front23.webp'),
    alt: 'Stripe customer reconciliation',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front24.webp',
    description: 'slides.teamChallenge.stripe_typing',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front24.webp'),
    alt: 'Stripe typed enums and fixtures',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front25.webp',
    description: 'slides.teamChallenge.stripe_endpoints',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front25.webp'),
    alt: 'Stripe REST endpoints',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front26.webp',
    description: 'slides.teamChallenge.cert_template',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front26.webp'),
    alt: 'Certificate template flattening',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front27.webp',
    description: 'slides.teamChallenge.cert_authz',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front27.webp'),
    alt: 'Certificate authorization checks',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front28.webp',
    description: 'slides.teamChallenge.cert_validation',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front28.webp'),
    alt: 'Joi date format validation',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front29.webp',
    description: 'slides.teamChallenge.test_combinatorial',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front29.webp'),
    alt: 'Combinatorial test scenario generation',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front30.webp',
    description: 'slides.teamChallenge.test_fixtures',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front30.webp'),
    alt: 'Shared fixtures and mocks',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front31.webp',
    description: 'slides.teamChallenge.test_drove_design',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front31.webp'),
    alt: 'Tests drove production design',
    projectName: 'teamChallenge',
  },
];

export const DataCarousel2D: CarouselProjectImg[] = [
  ...teamChallenge,
  ...project('ABS', 29, 'ABS front'),
  ...project('karamonVideo', 11, 'karamonVideo front'),
  ...project('nastyaPhoto', 12, 'nastyaPhoto front'),
  ...project('weatherReact', 14, 'weatherReact front'),
  ...project('casinoGame', 9, 'casinoGame front'),
  ...project('portfolio', 17, 'portfolio front'),
  ...project('kayayoga', 12, 'kayayoga front'),
  ...project('n8nWorkflows', 8, 'n8n workflow'),
  ...project('mcpServer', 6, 'MCP Server'),
  ...project('nativaLumi', 4, 'Nativa Lumi'),
  ...project('alexartia', 8, 'Alexartia'),
  ...project('cityGames', 6, 'City Games'),
  ...project('lucioleQuest', 9, 'Luciole Quest'),
  ...project('pmsGateway', 8, 'PMS Gateway API'),
];
