import { CarouselProjectImg } from '../../types/projects';

export const DataCarousel2D: CarouselProjectImg[] = [
  {
    imageName: 'front1.webp',
    description: 'slides.teamChallenge.stripe_di',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front1.webp'),
    alt: 'Stripe service architecture',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front2.webp',
    description: 'slides.teamChallenge.stripe_transformer',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front2.webp'),
    alt: 'Stripe transformer layer',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front3.webp',
    description: 'slides.teamChallenge.stripe_reconcile',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front3.webp'),
    alt: 'Stripe customer reconciliation',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front4.webp',
    description: 'slides.teamChallenge.stripe_typing',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front4.webp'),
    alt: 'Stripe typed enums and fixtures',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front5.webp',
    description: 'slides.teamChallenge.stripe_endpoints',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front5.webp'),
    alt: 'Stripe REST endpoints',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front6.webp',
    description: 'slides.teamChallenge.cert_template',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front6.webp'),
    alt: 'Certificate template flattening',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front7.webp',
    description: 'slides.teamChallenge.cert_adaptive',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front7.webp'),
    alt: 'Certificate adaptive template selection',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front8.webp',
    description: 'slides.teamChallenge.cert_authz',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front8.webp'),
    alt: 'Certificate authorization checks',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front9.webp',
    description: 'slides.teamChallenge.cert_validation',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front9.webp'),
    alt: 'Joi date format validation',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front10.webp',
    description: 'slides.teamChallenge.auth_guard',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front10.webp'),
    alt: 'withAuthGuard HOC',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front11.webp',
    description: 'slides.teamChallenge.auth_returnto',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front11.webp'),
    alt: 'returnTo preservation via appState',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front12.webp',
    description: 'slides.teamChallenge.auth_refresh',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front1.webp'),
    alt: 'Auth0 refresh tokens + invalid_grant',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front13.webp',
    description: 'slides.teamChallenge.auth_public',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front1.webp'),
    alt: 'Public route awareness',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front14.webp',
    description: 'slides.teamChallenge.rq_factory',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front1.webp'),
    alt: 'createUseQuery factory',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front15.webp',
    description: 'slides.teamChallenge.rq_userstatus',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front1.webp'),
    alt: 'useUserStatus domain hook',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front16.webp',
    description: 'slides.teamChallenge.rq_gating',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front1.webp'),
    alt: 'Query gating with enabled flag',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front17.webp',
    description: 'slides.teamChallenge.team_helper',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front1.webp'),
    alt: 'getCandidatesForExistingTeam pure helper',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front18.webp',
    description: 'slides.teamChallenge.team_invariants',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front1.webp'),
    alt: 'Domain invariants with throw guards',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front19.webp',
    description: 'slides.teamChallenge.team_stepper',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front1.webp'),
    alt: 'Join flow stepper state machine',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front20.webp',
    description: 'slides.teamChallenge.team_pagination',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front1.webp'),
    alt: 'Backend pagination with getPage util',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front21.webp',
    description: 'slides.teamChallenge.team_decisions',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front1.webp'),
    alt: 'Vacancies UI with decision statuses',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front22.webp',
    description: 'slides.teamChallenge.test_combinatorial',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front1.webp'),
    alt: 'Combinatorial test scenario generation',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front23.webp',
    description: 'slides.teamChallenge.test_fixtures',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front1.webp'),
    alt: 'Shared fixtures and mocks',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front24.webp',
    description: 'slides.teamChallenge.test_drove_design',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front1.webp'),
    alt: 'Tests drove production design',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front25.webp',
    description: 'slides.teamChallenge.ui_styled',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front1.webp'),
    alt: 'Styled components with theme tokens',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front26.webp',
    description: 'slides.teamChallenge.ui_context',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front1.webp'),
    alt: 'Avatar Context to avoid prop drilling',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front27.webp',
    description: 'slides.teamChallenge.ui_mobile',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front1.webp'),
    alt: 'Dedicated mobile components',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front28.webp',
    description: 'slides.teamChallenge.ui_i18n',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front1.webp'),
    alt: 'i18n from day one',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front1.webp',
    description: 'front1',
    general: false,
    src: require('../../images/MyProjects/Front/ABS/front1.webp'),
    alt: 'ABS front',
    projectName: 'ABS',
  },
  {
    imageName: 'front2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/ABS/front2.webp'),
    alt: 'ABS front',
    projectName: 'ABS',
  },
  {
    imageName: 'front3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/ABS/front3.webp'),
    alt: 'ABS front',
    projectName: 'ABS',
  },
  {
    imageName: 'front4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/ABS/front4.webp'),
    alt: 'ABS front',
    projectName: 'ABS',
  },
  {
    imageName: 'front5.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/ABS/front5.webp'),
    alt: 'ABS front',
    projectName: 'ABS',
  },
  {
    imageName: 'front6.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/ABS/front6.webp'),
    alt: 'ABS front',
    projectName: 'ABS',
  },
  {
    imageName: 'front7.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/ABS/front7.webp'),
    alt: 'ABS front',
    projectName: 'ABS',
  },
  {
    imageName: 'front8.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/ABS/front8.webp'),
    alt: 'ABS front',
    projectName: 'ABS',
  },
  {
    imageName: 'front9.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/ABS/front9.webp'),
    alt: 'ABS front',
    projectName: 'ABS',
  },
  {
    imageName: 'front10.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/ABS/front10.webp'),
    alt: 'ABS front',
    projectName: 'ABS',
  },
  {
    imageName: 'front11.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/ABS/front11.webp'),
    alt: 'ABS front',
    projectName: 'ABS',
  },
  {
    imageName: 'front12.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/ABS/front12.webp'),
    alt: 'ABS front',
    projectName: 'ABS',
  },
  {
    imageName: 'front13.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/ABS/front13.webp'),
    alt: 'ABS maquette',
    projectName: 'ABS',
  },
  {
    imageName: 'front14.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/ABS/front14.webp'),
    alt: 'ABS maquette mobile',
    projectName: 'ABS',
  },

  {
    imageName: 'front1.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/karamonVideo/front1.webp'),
    alt: 'karamonVideo front',
    projectName: 'karamonVideo',
  },
  {
    imageName: 'front2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/karamonVideo/front2.webp'),
    alt: 'karamonVideo front',
    projectName: 'karamonVideo',
  },
  {
    imageName: 'front3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/karamonVideo/front3.webp'),
    alt: 'karamonVideo front',
    projectName: 'karamonVideo',
  },
  {
    imageName: 'front4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/karamonVideo/front4.webp'),
    alt: 'karamonVideo front',
    projectName: 'karamonVideo',
  },
  {
    imageName: 'front5.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/karamonVideo/front5.webp'),
    alt: 'karamonVideo front',
    projectName: 'karamonVideo',
  },

  {
    imageName: 'front1.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/nastyaPhoto/front1.webp'),
    alt: 'nastyaPhoto front',
    projectName: 'nastyaPhoto',
  },
  {
    imageName: 'front2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/nastyaPhoto/front2.webp'),
    alt: 'nastyaPhoto front',
    projectName: 'nastyaPhoto',
  },
  {
    imageName: 'front3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/nastyaPhoto/front3.webp'),
    alt: 'nastyaPhoto front',
    projectName: 'nastyaPhoto',
  },
  {
    imageName: 'front4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/nastyaPhoto/front4.webp'),
    alt: 'nastyaPhoto front',
    projectName: 'nastyaPhoto',
  },
  {
    imageName: 'front5.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/nastyaPhoto/front5.webp'),
    alt: 'nastyaPhoto front',
    projectName: 'nastyaPhoto',
  },

  {
    imageName: 'front1.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/weatherReact/front1.webp'),
    alt: 'weatherReact front',
    projectName: 'weatherReact',
  },
  {
    imageName: 'front2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/weatherReact/front2.webp'),
    alt: 'weatherReact front',
    projectName: 'weatherReact',
  },
  {
    imageName: 'front3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/weatherReact/front3.webp'),
    alt: 'weatherReact front',
    projectName: 'weatherReact',
  },
  {
    imageName: 'front4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/weatherReact/front4.webp'),
    alt: 'weatherReact front',
    projectName: 'weatherReact',
  },
  {
    imageName: 'front5.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/weatherReact/front5.webp'),
    alt: 'weatherReact front',
    projectName: 'weatherReact',
  },
  {
    imageName: 'front6.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/weatherReact/front6.webp'),
    alt: 'weatherReact front',
    projectName: 'weatherReact',
  },
  {
    imageName: 'front7.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/weatherReact/front7.webp'),
    alt: 'weatherReact front',
    projectName: 'weatherReact',
  },
  {
    imageName: 'front8.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/weatherReact/front8.webp'),
    alt: 'weatherReact front',
    projectName: 'weatherReact',
  },

  {
    imageName: 'front1.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/casinoGame/front1.webp'),
    alt: 'casinoGame front',
    projectName: 'casinoGame',
  },
  {
    imageName: 'front2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/casinoGame/front2.webp'),
    alt: 'casinoGame front',
    projectName: 'casinoGame',
  },
  {
    imageName: 'front3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/casinoGame/front3.webp'),
    alt: 'casinoGame front',
    projectName: 'casinoGame',
  },
  {
    imageName: 'front4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/casinoGame/front4.webp'),
    alt: 'casinoGame front',
    projectName: 'casinoGame',
  },

  {
    imageName: 'front1.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/portfolio/front1.webp'),
    alt: 'portfolio front',
    projectName: 'portfolio',
  },
  {
    imageName: 'front2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/portfolio/front2.webp'),
    alt: 'portfolio front',
    projectName: 'portfolio',
  },
  {
    imageName: 'front3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/portfolio/front3.webp'),
    alt: 'portfolio front',
    projectName: 'portfolio',
  },
  {
    imageName: 'front4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/portfolio/front4.webp'),
    alt: 'portfolio front',
    projectName: 'portfolio',
  },
  {
    imageName: 'front5.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/portfolio/front5.webp'),
    alt: 'portfolio front',
    projectName: 'portfolio',
  },
  {
    imageName: 'front6.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/portfolio/front6.webp'),
    alt: 'portfolio front',
    projectName: 'portfolio',
  },
  {
    imageName: 'front7.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/portfolio/front7.webp'),
    alt: 'portfolio front',
    projectName: 'portfolio',
  },
  {
    imageName: 'front8.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/portfolio/front8.webp'),
    alt: 'portfolio front',
    projectName: 'portfolio',
  },
  {
    imageName: 'front9.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/portfolio/front9.webp'),
    alt: 'portfolio front',
    projectName: 'portfolio',
  },
  {
    imageName: 'front10.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/portfolio/front10.webp'),
    alt: 'portfolio front',
    projectName: 'portfolio',
  },
  {
    imageName: 'front1.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/kayayoga/front1.webp'),
    alt: 'kayayoga front',
    projectName: 'kayayoga',
  },
  {
    imageName: 'front2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/kayayoga/front2.webp'),
    alt: 'kayayoga front',
    projectName: 'kayayoga',
  },
  {
    imageName: 'front3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/kayayoga/front3.webp'),
    alt: 'kayayoga front',
    projectName: 'kayayoga',
  },
  {
    imageName: 'front4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/kayayoga/front4.webp'),
    alt: 'kayayoga front',
    projectName: 'kayayoga',
  },
  {
    imageName: 'front5.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/kayayoga/front5.webp'),
    alt: 'kayayoga front',
    projectName: 'kayayoga',
  },
  {
    imageName: 'front6.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/kayayoga/front6.webp'),
    alt: 'kayayoga front',
    projectName: 'kayayoga',
  },
  {
    imageName: 'front7.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/kayayoga/front7.webp'),
    alt: 'kayayoga front',
    projectName: 'kayayoga',
  },

  {
    imageName: 'front1.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/n8nWorkflows/front1.webp'),
    alt: 'n8n workflow',
    projectName: 'n8nWorkflows',
  },
  {
    imageName: 'front2.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/n8nWorkflows/front2.webp'),
    alt: 'n8n workflow',
    projectName: 'n8nWorkflows',
  },
  {
    imageName: 'front3.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/n8nWorkflows/front3.webp'),
    alt: 'n8n workflow',
    projectName: 'n8nWorkflows',
  },
  {
    imageName: 'front4.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/n8nWorkflows/front4.webp'),
    alt: 'n8n workflow',
    projectName: 'n8nWorkflows',
  },
  {
    imageName: 'front5.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/n8nWorkflows/front5.webp'),
    alt: 'n8n workflow',
    projectName: 'n8nWorkflows',
  },
  {
    imageName: 'front6.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/n8nWorkflows/front6.webp'),
    alt: 'n8n workflow',
    projectName: 'n8nWorkflows',
  },
  {
    imageName: 'front7.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/n8nWorkflows/front7.webp'),
    alt: 'n8n workflow',
    projectName: 'n8nWorkflows',
  },
  {
    imageName: 'front8.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/n8nWorkflows/front8.webp'),
    alt: 'n8n workflow',
    projectName: 'n8nWorkflows',
  },

  {
    imageName: 'front1.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/mcpServer/front1.webp'),
    alt: 'MCP Server',
    projectName: 'mcpServer',
  },
  {
    imageName: 'front2.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/mcpServer/front2.webp'),
    alt: 'MCP Server',
    projectName: 'mcpServer',
  },
  {
    imageName: 'front3.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/mcpServer/front3.webp'),
    alt: 'MCP Server',
    projectName: 'mcpServer',
  },
  {
    imageName: 'front4.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/mcpServer/front4.webp'),
    alt: 'MCP Server',
    projectName: 'mcpServer',
  },
  {
    imageName: 'front5.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/mcpServer/front5.webp'),
    alt: 'MCP Server',
    projectName: 'mcpServer',
  },
  {
    imageName: 'front6.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/mcpServer/front6.webp'),
    alt: 'MCP Server',
    projectName: 'mcpServer',
  },

  {
    imageName: 'front1.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/nativaLumi/front1.webp'),
    alt: 'Nativa Lumi',
    projectName: 'nativaLumi',
  },
  {
    imageName: 'front2.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/nativaLumi/front2.webp'),
    alt: 'Nativa Lumi',
    projectName: 'nativaLumi',
  },
  {
    imageName: 'front3.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/nativaLumi/front3.webp'),
    alt: 'Nativa Lumi',
    projectName: 'nativaLumi',
  },
  {
    imageName: 'front4.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/nativaLumi/front4.webp'),
    alt: 'Nativa Lumi',
    projectName: 'nativaLumi',
  },

  {
    imageName: 'front1.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/alexartia/front1.webp'),
    alt: 'Alexartia',
    projectName: 'alexartia',
  },
  {
    imageName: 'front2.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/alexartia/front2.webp'),
    alt: 'Alexartia',
    projectName: 'alexartia',
  },
  {
    imageName: 'front3.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/alexartia/front3.webp'),
    alt: 'Alexartia',
    projectName: 'alexartia',
  },
  {
    imageName: 'front4.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/alexartia/front4.webp'),
    alt: 'Alexartia',
    projectName: 'alexartia',
  },
  {
    imageName: 'front5.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/alexartia/front5.webp'),
    alt: 'Alexartia',
    projectName: 'alexartia',
  },
  {
    imageName: 'front6.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/alexartia/front6.webp'),
    alt: 'Alexartia',
    projectName: 'alexartia',
  },
  {
    imageName: 'front7.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/alexartia/front7.webp'),
    alt: 'Alexartia',
    projectName: 'alexartia',
  },
  {
    imageName: 'front8.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/alexartia/front8.webp'),
    alt: 'Alexartia',
    projectName: 'alexartia',
  },

  {
    imageName: 'front1.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/cityGames/front1.webp'),
    alt: 'City Games',
    projectName: 'cityGames',
  },
  {
    imageName: 'front2.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/cityGames/front2.webp'),
    alt: 'City Games',
    projectName: 'cityGames',
  },
  {
    imageName: 'front3.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/cityGames/front3.webp'),
    alt: 'City Games',
    projectName: 'cityGames',
  },
  {
    imageName: 'front4.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/cityGames/front4.webp'),
    alt: 'City Games',
    projectName: 'cityGames',
  },
  {
    imageName: 'front5.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/cityGames/front5.webp'),
    alt: 'City Games',
    projectName: 'cityGames',
  },
  {
    imageName: 'front6.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/cityGames/front6.webp'),
    alt: 'City Games',
    projectName: 'cityGames',
  },

  {
    imageName: 'front1.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/lucioleQuest/front1.webp'),
    alt: 'Luciole Quest',
    projectName: 'lucioleQuest',
  },
  {
    imageName: 'front2.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/lucioleQuest/front2.webp'),
    alt: 'Luciole Quest',
    projectName: 'lucioleQuest',
  },
  {
    imageName: 'front3.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/lucioleQuest/front3.webp'),
    alt: 'Luciole Quest',
    projectName: 'lucioleQuest',
  },
  {
    imageName: 'front4.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/lucioleQuest/front4.webp'),
    alt: 'Luciole Quest',
    projectName: 'lucioleQuest',
  },
  {
    imageName: 'front5.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/lucioleQuest/front5.webp'),
    alt: 'Luciole Quest',
    projectName: 'lucioleQuest',
  },
  {
    imageName: 'front6.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/lucioleQuest/front6.webp'),
    alt: 'Luciole Quest',
    projectName: 'lucioleQuest',
  },
  {
    imageName: 'front7.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/lucioleQuest/front7.webp'),
    alt: 'Luciole Quest',
    projectName: 'lucioleQuest',
  },
  {
    imageName: 'front8.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/lucioleQuest/front8.webp'),
    alt: 'Luciole Quest',
    projectName: 'lucioleQuest',
  },
  {
    imageName: 'front9.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/lucioleQuest/front9.webp'),
    alt: 'Luciole Quest',
    projectName: 'lucioleQuest',
  },

  {
    imageName: 'front1.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/pmsGateway/front1.webp'),
    alt: 'PMS Gateway API',
    projectName: 'pmsGateway',
  },
  {
    imageName: 'front2.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/pmsGateway/front2.webp'),
    alt: 'PMS Gateway API',
    projectName: 'pmsGateway',
  },
  {
    imageName: 'front3.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/pmsGateway/front3.webp'),
    alt: 'PMS Gateway API',
    projectName: 'pmsGateway',
  },
  {
    imageName: 'front4.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/pmsGateway/front4.webp'),
    alt: 'PMS Gateway API',
    projectName: 'pmsGateway',
  },
  {
    imageName: 'front5.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/pmsGateway/front5.webp'),
    alt: 'PMS Gateway API',
    projectName: 'pmsGateway',
  },
  {
    imageName: 'front6.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/pmsGateway/front6.webp'),
    alt: 'PMS Gateway API',
    projectName: 'pmsGateway',
  },
  {
    imageName: 'front7.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/pmsGateway/front7.webp'),
    alt: 'PMS Gateway API',
    projectName: 'pmsGateway',
  },
  {
    imageName: 'front8.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Front/pmsGateway/front8.webp'),
    alt: 'PMS Gateway API',
    projectName: 'pmsGateway',
  },
];
