import { CarouselProjectImg } from '../../types/projects';

export const DataCarousel2DBack: CarouselProjectImg[] = [
  {
    imageName: 'back1.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/seaLife/back1.webp'),
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/seaLife/back2.webp'),
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/seaLife/back3.webp'),
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/seaLife/back4.webp'),
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/seaLife/back5.webp'),
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back6.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/seaLife/back6.webp'),
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back7.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/seaLife/back7.webp'),
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back8.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/seaLife/back8.webp'),
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back9.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/seaLife/back9.webp'),
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  //////
  {
    imageName: 'back1.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Back/teamChallenge/back1.webp'),
    alt: 'main page',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'back2.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Back/teamChallenge/back2.webp'),
    alt: 'main page 2 screen',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'back3.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Back/teamChallenge/back3.webp'),
    alt: 'main page 3 screen',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'back4.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Back/teamChallenge/back4.webp'),
    alt: 'user account',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'back5.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Back/teamChallenge/back5.webp'),
    alt: 'page my progects',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'back6.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Back/teamChallenge/back6.webp'),
    alt: 'teams',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'back7.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Back/teamChallenge/back7.webp'),
    alt: 'mobile',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'back8.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Back/teamChallenge/back8.webp'),
    alt: 'mobile',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'back9.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Back/teamChallenge/back9.webp'),
    alt: 'join',
    projectName: 'teamChallenge',
  },

  {
    imageName: 'back1.webp',
    description: 'back1',
    general: false,
    src: require('../../images/MyProjects/Back/ABS/back1.webp'),
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ABS/back2.webp'),
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ABS/back3.webp'),
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ABS/back4.webp'),
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ABS/back5.webp'),
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back6.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ABS/back6.webp'),
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back7.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ABS/back7.webp'),
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back8.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ABS/back8.webp'),
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back9.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ABS/back9.webp'),
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back10.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ABS/back10.webp'),
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back11.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ABS/back11.webp'),
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back12.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ABS/back12.webp'),
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back13.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ABS/back13.webp'),
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back14.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ABS/back14.webp'),
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back15.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ABS/back15.webp'),
    alt: 'ABS back',
    projectName: 'ABS',
  },

  {
    imageName: 'back1.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/karamonVideo/back1.webp'),
    alt: 'karamonVideo back',
    projectName: 'karamonVideo',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/karamonVideo/back2.webp'),
    alt: 'karamonVideo back',
    projectName: 'karamonVideo',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/karamonVideo/back3.webp'),
    alt: 'karamonVideo back',
    projectName: 'karamonVideo',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/karamonVideo/back4.webp'),
    alt: 'karamonVideo back',
    projectName: 'karamonVideo',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/karamonVideo/back5.webp'),
    alt: 'karamonVideo back',
    projectName: 'karamonVideo',
  },
  {
    imageName: 'back6.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/karamonVideo/back6.webp'),
    alt: 'karamonVideo back',
    projectName: 'karamonVideo',
  },

  {
    imageName: 'back1.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/nastyaPhoto/back1.webp'),
    alt: 'nastyaPhoto back',
    projectName: 'nastyaPhoto',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/nastyaPhoto/back2.webp'),
    alt: 'nastyaPhoto back',
    projectName: 'nastyaPhoto',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/nastyaPhoto/back3.webp'),
    alt: 'nastyaPhoto back',
    projectName: 'nastyaPhoto',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/nastyaPhoto/back4.webp'),
    alt: 'nastyaPhoto back',
    projectName: 'nastyaPhoto',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/nastyaPhoto/back5.webp'),
    alt: 'nastyaPhoto back',
    projectName: 'nastyaPhoto',
  },
  {
    imageName: 'back6.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/nastyaPhoto/back6.webp'),
    alt: 'nastyaPhoto back',
    projectName: 'nastyaPhoto',
  },

  {
    imageName: 'back1.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/weatherReact/back1.webp'),
    alt: 'weatherReact back',
    projectName: 'weatherReact',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/weatherReact/back2.webp'),
    alt: 'weatherReact back',
    projectName: 'weatherReact',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/weatherReact/back3.webp'),
    alt: 'weatherReact back',
    projectName: 'weatherReact',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/weatherReact/back4.webp'),
    alt: 'weatherReact back',
    projectName: 'weatherReact',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/weatherReact/back5.webp'),
    alt: 'weatherReact back',
    projectName: 'weatherReact',
  },

  {
    imageName: 'back1.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/casinoGame/back1.webp'),
    alt: 'casinoGame back',
    projectName: 'casinoGame',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/casinoGame/back2.webp'),
    alt: 'casinoGame back',
    projectName: 'casinoGame',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/casinoGame/back3.webp'),
    alt: 'casinoGame back',
    projectName: 'casinoGame',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/casinoGame/back4.webp'),
    alt: 'casinoGame back',
    projectName: 'casinoGame',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/casinoGame/back5.webp'),
    alt: 'casinoGame back',
    projectName: 'casinoGame',
  },

  {
    imageName: 'back1.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/portfolio/back1.webp'),
    alt: 'portfolio back',
    projectName: 'portfolio',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/portfolio/back2.webp'),
    alt: 'portfolio back',
    projectName: 'portfolio',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/portfolio/back3.webp'),
    alt: 'portfolio back',
    projectName: 'portfolio',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/portfolio/back4.webp'),
    alt: 'portfolio back',
    projectName: 'portfolio',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/portfolio/back5.webp'),
    alt: 'portfolio back',
    projectName: 'portfolio',
  },
  {
    imageName: 'back6.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/portfolio/back6.webp'),
    alt: 'portfolio back',
    projectName: 'portfolio',
  },
  {
    imageName: 'back7.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/portfolio/back7.webp'),
    alt: 'portfolio back',
    projectName: 'portfolio',
  },
  {
    imageName: 'back1.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/kayayoga/back1.webp'),
    alt: 'kayayoga back',
    projectName: 'kayayoga',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/kayayoga/back2.webp'),
    alt: 'kayayoga back',
    projectName: 'kayayoga',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/kayayoga/back3.webp'),
    alt: 'kayayoga back',
    projectName: 'kayayoga',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/kayayoga/back4.webp'),
    alt: 'kayayoga back',
    projectName: 'kayayoga',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/kayayoga/back5.webp'),
    alt: 'kayayoga back',
    projectName: 'kayayoga',
  },
];
