import { CarouselProjectImg } from '../../types/projects';

export const DataCarousel2DBack: CarouselProjectImg[] = [
  {
    imageName: 'back1.webp',
    description: 'back1',
    general: false,
    src: require('../../images/MyProjects/Back/assoFacTory/back1.webp'),
    alt: 'AssoFacTory back',
    projectName: 'assoFacTory',
  },
  {
    imageName: 'back2.webp',
    description: 'back2',
    general: false,
    src: require('../../images/MyProjects/Back/assoFacTory/back2.webp'),
    alt: 'AssoFacTory back',
    projectName: 'assoFacTory',
  },
  {
    imageName: 'back3.webp',
    description: 'back3',
    general: false,
    src: require('../../images/MyProjects/Back/assoFacTory/back3.webp'),
    alt: 'AssoFacTory back',
    projectName: 'assoFacTory',
  },
  {
    imageName: 'back4.webp',
    description: 'back4',
    general: false,
    src: require('../../images/MyProjects/Back/assoFacTory/back4.webp'),
    alt: 'AssoFacTory back',
    projectName: 'assoFacTory',
  },
  {
    imageName: 'back5.webp',
    description: 'back5',
    general: false,
    src: require('../../images/MyProjects/Back/assoFacTory/back5.webp'),
    alt: 'AssoFacTory back',
    projectName: 'assoFacTory',
  },
  {
    imageName: 'back6.webp',
    description: 'back6',
    general: false,
    src: require('../../images/MyProjects/Back/assoFacTory/back6.webp'),
    alt: 'AssoFacTory back',
    projectName: 'assoFacTory',
  },
  {
    imageName: 'back7.webp',
    description: 'back7',
    general: false,
    src: require('../../images/MyProjects/Back/assoFacTory/back7.webp'),
    alt: 'AssoFacTory back',
    projectName: 'assoFacTory',
  },
  {
    imageName: 'back8.webp',
    description: 'back8',
    general: false,
    src: require('../../images/MyProjects/Back/assoFacTory/back8.webp'),
    alt: 'AssoFacTory back',
    projectName: 'assoFacTory',
  },
  {
    imageName: 'back9.webp',
    description: 'back9',
    general: false,
    src: require('../../images/MyProjects/Back/assoFacTory/back9.webp'),
    alt: 'AssoFacTory back',
    projectName: 'assoFacTory',
  },
  {
    imageName: 'back10.webp',
    description: 'back10',
    general: false,
    src: require('../../images/MyProjects/Back/assoFacTory/back10.webp'),
    alt: 'AssoFacTory back',
    projectName: 'assoFacTory',
  },
  {
    imageName: 'back11.webp',
    description: 'back11',
    general: false,
    src: require('../../images/MyProjects/Back/assoFacTory/back11.webp'),
    alt: 'AssoFacTory back',
    projectName: 'assoFacTory',
  },

  {
    imageName: 'back1.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/connectify/back1.webp'),
    alt: 'Connectify back',
    projectName: 'connectify',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/connectify/back2.webp'),
    alt: 'Connectify back',
    projectName: 'connectify',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/connectify/back3.webp'),
    alt: 'Connectify back',
    projectName: 'connectify',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/connectify/back4.webp'),
    alt: 'Connectify back',
    projectName: 'connectify',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/connectify/back5.webp'),
    alt: 'Connectify back',
    projectName: 'connectify',
  },
  {
    imageName: 'back6.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/connectify/back6.webp'),
    alt: 'Connectify back',
    projectName: 'connectify',
  },
  {
    imageName: 'back7.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/connectify/back7.webp'),
    alt: 'Connectify back',
    projectName: 'connectify',
  },
  {
    imageName: 'back8.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/connectify/back8.webp'),
    alt: 'Connectify back',
    projectName: 'connectify',
  },
  {
    imageName: 'back9.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/connectify/back9.webp'),
    alt: 'Connectify back',
    projectName: 'connectify',
  },
  {
    imageName: 'back10.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/connectify/back10.webp'),
    alt: 'Connectify back',
    projectName: 'connectify',
  },
  {
    imageName: 'back11.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/connectify/back11.webp'),
    alt: 'Connectify back',
    projectName: 'connectify',
  },

  {
    imageName: 'back1.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/garage/back1.webp'),
    alt: 'Garage back',
    projectName: 'garage',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/garage/back2.webp'),
    alt: 'Garage back',
    projectName: 'garage',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/garage/back3.webp'),
    alt: 'Garage back',
    projectName: 'garage',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/garage/back4.webp'),
    alt: 'Garage back',
    projectName: 'garage',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/garage/back5.webp'),
    alt: 'Garage back',
    projectName: 'garage',
  },
  {
    imageName: 'back6.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/garage/back6.webp'),
    alt: 'Garage back',
    projectName: 'garage',
  },
  {
    imageName: 'back7.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/garage/back7.webp'),
    alt: 'Garage back',
    projectName: 'garage',
  },

  {
    imageName: 'back1.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/seaLife/back1.webp'),
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/seaLife/back2.webp'),
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/seaLife/back3.webp'),
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/seaLife/back4.webp'),
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/seaLife/back5.webp'),
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back6.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/seaLife/back6.webp'),
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back7.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/seaLife/back7.webp'),
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back8.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/seaLife/back8.webp'),
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back9.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/seaLife/back9.webp'),
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  //////
  {
    imageName: 'back1.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Back/teamChallenge/back1.webp'),
    alt: 'main page',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'back2.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Back/teamChallenge/back2.webp'),
    alt: 'main page 2 screen',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'back3.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Back/teamChallenge/back3.webp'),
    alt: 'main page 3 screen',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'back4.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Back/teamChallenge/back4.webp'),
    alt: 'user account',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'back5.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Back/teamChallenge/back5.webp'),
    alt: 'page my progects',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'back6.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Back/teamChallenge/back6.webp'),
    alt: 'teams',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'back7.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Back/teamChallenge/back7.webp'),
    alt: 'mobile',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'back8.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Back/teamChallenge/back8.webp'),
    alt: 'mobile',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'back9.webp',
    description: '',
    general: false,
    src: require('../../images/MyProjects/Back/teamChallenge/back9.webp'),
    alt: 'join',
    projectName: 'teamChallenge',
  },

  {
    imageName: 'back1.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/diamondCollection/back1.webp'),
    alt: 'diamondCollection back',
    projectName: 'diamondCollection',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/diamondCollection/back2.webp'),
    alt: 'diamondCollection back',
    projectName: 'diamondCollection',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/diamondCollection/back3.webp'),
    alt: 'diamondCollection back',
    projectName: 'diamondCollection',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/diamondCollection/back4.webp'),
    alt: 'diamondCollection back',
    projectName: 'diamondCollection',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/diamondCollection/back5.webp'),
    alt: 'diamondCollection back',
    projectName: 'diamondCollection',
  },
  {
    imageName: 'back6.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/diamondCollection/back6.webp'),
    alt: 'diamondCollection back',
    projectName: 'diamondCollection',
  },
  {
    imageName: 'back7.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/diamondCollection/back7.webp'),
    alt: 'diamondCollection back',
    projectName: 'diamondCollection',
  },

  {
    imageName: 'back1.webp',
    description: 'back1',
    general: false,
    src: require('../../images/MyProjects/Back/ABS/back1.webp'),
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ABS/back2.webp'),
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ABS/back3.webp'),
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ABS/back4.webp'),
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ABS/back5.webp'),
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back6.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ABS/back6.webp'),
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back7.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ABS/back7.webp'),
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back8.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ABS/back8.webp'),
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back9.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ABS/back9.webp'),
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back10.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ABS/back10.webp'),
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back11.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ABS/back11.webp'),
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back12.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ABS/back12.webp'),
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back13.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ABS/back13.webp'),
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back14.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ABS/back14.webp'),
    alt: 'ABS back',
    projectName: 'ABS',
  },
  {
    imageName: 'back15.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ABS/back15.webp'),
    alt: 'ABS back',
    projectName: 'ABS',
  },

  {
    imageName: 'back1.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ekea/back1.webp'),
    alt: 'ekea code',
    projectName: 'ekea',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ekea/back2.webp'),
    alt: 'ekea code',
    projectName: 'ekea',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ekea/back3.webp'),
    alt: 'ekea code',
    projectName: 'ekea',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ekea/back4.webp'),
    alt: 'ekea code',
    projectName: 'ekea',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ekea/back5.webp'),
    alt: 'ekea code',
    projectName: 'ekea',
  },
  {
    imageName: 'back6.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ekea/back6.webp'),
    alt: 'ekea code',
    projectName: 'ekea',
  },
  {
    imageName: 'back7.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ekea/back7.webp'),
    alt: 'ekea code',
    projectName: 'ekea',
  },
  {
    imageName: 'back8.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/ekea/back8.webp'),
    alt: 'ekea code',
    projectName: 'ekea',
  },

  {
    imageName: 'back1.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/karamonVideo/back1.webp'),
    alt: 'karamonVideo back',
    projectName: 'karamonVideo',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/karamonVideo/back2.webp'),
    alt: 'karamonVideo back',
    projectName: 'karamonVideo',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/karamonVideo/back3.webp'),
    alt: 'karamonVideo back',
    projectName: 'karamonVideo',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/karamonVideo/back4.webp'),
    alt: 'karamonVideo back',
    projectName: 'karamonVideo',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/karamonVideo/back5.webp'),
    alt: 'karamonVideo back',
    projectName: 'karamonVideo',
  },
  {
    imageName: 'back6.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/karamonVideo/back6.webp'),
    alt: 'karamonVideo back',
    projectName: 'karamonVideo',
  },

  {
    imageName: 'back1.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/nastyaPhoto/back1.webp'),
    alt: 'nastyaPhoto back',
    projectName: 'nastyaPhoto',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/nastyaPhoto/back2.webp'),
    alt: 'nastyaPhoto back',
    projectName: 'nastyaPhoto',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/nastyaPhoto/back3.webp'),
    alt: 'nastyaPhoto back',
    projectName: 'nastyaPhoto',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/nastyaPhoto/back4.webp'),
    alt: 'nastyaPhoto back',
    projectName: 'nastyaPhoto',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/nastyaPhoto/back5.webp'),
    alt: 'nastyaPhoto back',
    projectName: 'nastyaPhoto',
  },
  {
    imageName: 'back6.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/nastyaPhoto/back6.webp'),
    alt: 'nastyaPhoto back',
    projectName: 'nastyaPhoto',
  },

  {
    imageName: 'back1.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/weatherReact/back1.webp'),
    alt: 'weatherReact back',
    projectName: 'weatherReact',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/weatherReact/back2.webp'),
    alt: 'weatherReact back',
    projectName: 'weatherReact',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/weatherReact/back3.webp'),
    alt: 'weatherReact back',
    projectName: 'weatherReact',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/weatherReact/back4.webp'),
    alt: 'weatherReact back',
    projectName: 'weatherReact',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/weatherReact/back5.webp'),
    alt: 'weatherReact back',
    projectName: 'weatherReact',
  },

  {
    imageName: 'back1.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/casinoGame/back1.webp'),
    alt: 'casinoGame back',
    projectName: 'casinoGame',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/casinoGame/back2.webp'),
    alt: 'casinoGame back',
    projectName: 'casinoGame',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/casinoGame/back3.webp'),
    alt: 'casinoGame back',
    projectName: 'casinoGame',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/casinoGame/back4.webp'),
    alt: 'casinoGame back',
    projectName: 'casinoGame',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/casinoGame/back5.webp'),
    alt: 'casinoGame back',
    projectName: 'casinoGame',
  },

  {
    imageName: 'back1.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/portfolio/back1.webp'),
    alt: 'portfolio back',
    projectName: 'portfolio',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/portfolio/back2.webp'),
    alt: 'portfolio back',
    projectName: 'portfolio',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/portfolio/back3.webp'),
    alt: 'portfolio back',
    projectName: 'portfolio',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/portfolio/back4.webp'),
    alt: 'portfolio back',
    projectName: 'portfolio',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/portfolio/back5.webp'),
    alt: 'portfolio back',
    projectName: 'portfolio',
  },
  {
    imageName: 'back6.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/portfolio/back6.webp'),
    alt: 'portfolio back',
    projectName: 'portfolio',
  },
  {
    imageName: 'back7.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/portfolio/back7.webp'),
    alt: 'portfolio back',
    projectName: 'portfolio',
  },
  {
    imageName: 'back1.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/kayayoga/back1.webp'),
    alt: 'kayayoga back',
    projectName: 'kayayoga',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/kayayoga/back2.webp'),
    alt: 'kayayoga back',
    projectName: 'kayayoga',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/kayayoga/back3.webp'),
    alt: 'kayayoga back',
    projectName: 'kayayoga',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/kayayoga/back4.webp'),
    alt: 'kayayoga back',
    projectName: 'kayayoga',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Back/kayayoga/back5.webp'),
    alt: 'kayayoga back',
    projectName: 'kayayoga',
  },
];
