import { CarouselProjectImg } from '../../types/projects';

export const DataCarousel2D: CarouselProjectImg[] = [
  {
    imageName: 'front1.webp',
    description: 'test',
    general: true,
    src: require('../../images/MyProjects/Front/seaLife/front1.webp'),
    alt: 'SeaLife front',
    projectName: 'SeaLife',
  },
  {
    imageName: 'front2.webp',
    description: 'test',
    general: true,
    src: require('../../images/MyProjects/Front/seaLife/front2.webp'),
    alt: 'SeaLife front',
    projectName: 'SeaLife',
  },
  {
    imageName: 'front3.webp',
    description: 'test',
    general: true,
    src: require('../../images/MyProjects/Front/seaLife/front3.webp'),
    alt: 'SeaLife front',
    projectName: 'SeaLife',
  },
  {
    imageName: 'front4.webp',
    description: 'test',
    general: true,
    src: require('../../images/MyProjects/Front/seaLife/front4.webp'),
    alt: 'SeaLife front',
    projectName: 'SeaLife',
  },
  {
    imageName: 'front5.webp',
    description: 'test',
    general: true,
    src: require('../../images/MyProjects/Front/seaLife/front5.webp'),
    alt: 'SeaLife front',
    projectName: 'SeaLife',
  },

  {
    imageName: 'front1.webp',
    description: 'main page',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front1.webp'),
    alt: 'main page',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front2.webp',
    description: 'main page 2 screen',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front2.webp'),
    alt: 'main page 2 screen',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front3.webp',
    description: 'main page 3 screen',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front3.webp'),
    alt: 'main page 3 screen',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front4.webp',
    description: 'user account',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front4.webp'),
    alt: 'user account',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front5.webp',
    description: 'page my progects',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front5.webp'),
    alt: 'page my progects',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front6.webp',
    description: 'teams',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front6.webp'),
    alt: 'teams',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front7.webp',
    description: 'mobile',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front7.webp'),
    alt: 'mobile',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front8.webp',
    description: 'mobile',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front8.webp'),
    alt: 'mobile',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front9.webp',
    description: 'join',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front9.webp'),
    alt: 'join',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front10.webp',
    description: 'join',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front10.webp'),
    alt: 'join',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front11.webp',
    description: 'join',
    general: false,
    src: require('../../images/MyProjects/Front/teamChallenge/front10.webp'),
    alt: 'join',
    projectName: 'teamChallenge',
  },
  {
    imageName: 'front1.webp',
    description: 'front1',
    general: false,
    src: require('../../images/MyProjects/Front/ABS/front1.webp'),
    alt: 'ABS front',
    projectName: 'ABS',
  },
  {
    imageName: 'front2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/ABS/front2.webp'),
    alt: 'ABS front',
    projectName: 'ABS',
  },
  {
    imageName: 'front3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/ABS/front3.webp'),
    alt: 'ABS front',
    projectName: 'ABS',
  },
  {
    imageName: 'front4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/ABS/front4.webp'),
    alt: 'ABS front',
    projectName: 'ABS',
  },
  {
    imageName: 'front5.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/ABS/front5.webp'),
    alt: 'ABS front',
    projectName: 'ABS',
  },
  {
    imageName: 'front6.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/ABS/front6.webp'),
    alt: 'ABS front',
    projectName: 'ABS',
  },
  {
    imageName: 'front7.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/ABS/front7.webp'),
    alt: 'ABS front',
    projectName: 'ABS',
  },
  {
    imageName: 'front8.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/ABS/front8.webp'),
    alt: 'ABS front',
    projectName: 'ABS',
  },
  {
    imageName: 'front9.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/ABS/front9.webp'),
    alt: 'ABS front',
    projectName: 'ABS',
  },
  {
    imageName: 'front10.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/ABS/front10.webp'),
    alt: 'ABS front',
    projectName: 'ABS',
  },
  {
    imageName: 'front11.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/ABS/front11.webp'),
    alt: 'ABS front',
    projectName: 'ABS',
  },
  {
    imageName: 'front12.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/ABS/front12.webp'),
    alt: 'ABS front',
    projectName: 'ABS',
  },
  {
    imageName: 'front13.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/ABS/front13.webp'),
    alt: 'ABS maquette',
    projectName: 'ABS',
  },
  {
    imageName: 'front14.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/ABS/front14.webp'),
    alt: 'ABS maquette mobile',
    projectName: 'ABS',
  },

  {
    imageName: 'front1.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/karamonVideo/front1.webp'),
    alt: 'karamonVideo front',
    projectName: 'karamonVideo',
  },
  {
    imageName: 'front2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/karamonVideo/front2.webp'),
    alt: 'karamonVideo front',
    projectName: 'karamonVideo',
  },
  {
    imageName: 'front3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/karamonVideo/front3.webp'),
    alt: 'karamonVideo front',
    projectName: 'karamonVideo',
  },
  {
    imageName: 'front4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/karamonVideo/front4.webp'),
    alt: 'karamonVideo front',
    projectName: 'karamonVideo',
  },
  {
    imageName: 'front5.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/karamonVideo/front5.webp'),
    alt: 'karamonVideo front',
    projectName: 'karamonVideo',
  },

  {
    imageName: 'front1.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/nastyaPhoto/front1.webp'),
    alt: 'nastyaPhoto front',
    projectName: 'nastyaPhoto',
  },
  {
    imageName: 'front2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/nastyaPhoto/front2.webp'),
    alt: 'nastyaPhoto front',
    projectName: 'nastyaPhoto',
  },
  {
    imageName: 'front3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/nastyaPhoto/front3.webp'),
    alt: 'nastyaPhoto front',
    projectName: 'nastyaPhoto',
  },
  {
    imageName: 'front4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/nastyaPhoto/front4.webp'),
    alt: 'nastyaPhoto front',
    projectName: 'nastyaPhoto',
  },
  {
    imageName: 'front5.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/nastyaPhoto/front5.webp'),
    alt: 'nastyaPhoto front',
    projectName: 'nastyaPhoto',
  },

  {
    imageName: 'front1.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/weatherReact/front1.webp'),
    alt: 'weatherReact front',
    projectName: 'weatherReact',
  },
  {
    imageName: 'front2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/weatherReact/front2.webp'),
    alt: 'weatherReact front',
    projectName: 'weatherReact',
  },
  {
    imageName: 'front3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/weatherReact/front3.webp'),
    alt: 'weatherReact front',
    projectName: 'weatherReact',
  },
  {
    imageName: 'front4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/weatherReact/front4.webp'),
    alt: 'weatherReact front',
    projectName: 'weatherReact',
  },
  {
    imageName: 'front5.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/weatherReact/front5.webp'),
    alt: 'weatherReact front',
    projectName: 'weatherReact',
  },
  {
    imageName: 'front6.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/weatherReact/front6.webp'),
    alt: 'weatherReact front',
    projectName: 'weatherReact',
  },
  {
    imageName: 'front7.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/weatherReact/front7.webp'),
    alt: 'weatherReact front',
    projectName: 'weatherReact',
  },
  {
    imageName: 'front8.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/weatherReact/front8.webp'),
    alt: 'weatherReact front',
    projectName: 'weatherReact',
  },

  {
    imageName: 'front1.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/casinoGame/front1.webp'),
    alt: 'casinoGame front',
    projectName: 'casinoGame',
  },
  {
    imageName: 'front2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/casinoGame/front2.webp'),
    alt: 'casinoGame front',
    projectName: 'casinoGame',
  },
  {
    imageName: 'front3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/casinoGame/front3.webp'),
    alt: 'casinoGame front',
    projectName: 'casinoGame',
  },
  {
    imageName: 'front4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/casinoGame/front4.webp'),
    alt: 'casinoGame front',
    projectName: 'casinoGame',
  },

  {
    imageName: 'front1.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/portfolio/front1.webp'),
    alt: 'portfolio front',
    projectName: 'portfolio',
  },
  {
    imageName: 'front2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/portfolio/front2.webp'),
    alt: 'portfolio front',
    projectName: 'portfolio',
  },
  {
    imageName: 'front3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/portfolio/front3.webp'),
    alt: 'portfolio front',
    projectName: 'portfolio',
  },
  {
    imageName: 'front4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/portfolio/front4.webp'),
    alt: 'portfolio front',
    projectName: 'portfolio',
  },
  {
    imageName: 'front5.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/portfolio/front5.webp'),
    alt: 'portfolio front',
    projectName: 'portfolio',
  },
  {
    imageName: 'front6.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/portfolio/front6.webp'),
    alt: 'portfolio front',
    projectName: 'portfolio',
  },
  {
    imageName: 'front7.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/portfolio/front7.webp'),
    alt: 'portfolio front',
    projectName: 'portfolio',
  },
  {
    imageName: 'front8.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/portfolio/front8.webp'),
    alt: 'portfolio front',
    projectName: 'portfolio',
  },
  {
    imageName: 'front9.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/portfolio/front9.webp'),
    alt: 'portfolio front',
    projectName: 'portfolio',
  },
  {
    imageName: 'front10.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/portfolio/front10.webp'),
    alt: 'portfolio front',
    projectName: 'portfolio',
  },
  {
    imageName: 'front1.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/kayayoga/front1.webp'),
    alt: 'kayayoga front',
    projectName: 'kayayoga',
  },
  {
    imageName: 'front2.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/kayayoga/front2.webp'),
    alt: 'kayayoga front',
    projectName: 'kayayoga',
  },
  {
    imageName: 'front3.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/kayayoga/front3.webp'),
    alt: 'kayayoga front',
    projectName: 'kayayoga',
  },
  {
    imageName: 'front4.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/kayayoga/front4.webp'),
    alt: 'kayayoga front',
    projectName: 'kayayoga',
  },
  {
    imageName: 'front5.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/kayayoga/front5.webp'),
    alt: 'kayayoga front',
    projectName: 'kayayoga',
  },
  {
    imageName: 'front6.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/kayayoga/front6.webp'),
    alt: 'kayayoga front',
    projectName: 'kayayoga',
  },
  {
    imageName: 'front7.webp',
    description: 'test',
    general: false,
    src: require('../../images/MyProjects/Front/kayayoga/front7.webp'),
    alt: 'kayayoga front',
    projectName: 'kayayoga',
  },
];
