import { Carousel3d } from '../../types/projects';

export const imagesCarousel: Carousel3d[] = [
  {
    imageName: 'img1.webp', //teamchallenge
    descriptions: 'React|Styled-components|Typecript|Mui-material|PostgreSQL|GitHub|Work in the team',
    linkGit: 'private',
    linkProject: 'https://teamchallenge.io/',
    linkVideo: 'https://youtu.be/b_6AnXj5OxM',
    src: '',
    degY: 0,
    alt: 'Plateforme Web pour les juniors, qui rassemble une équipe interfonctionnelle pour son premier projet',
    projectName: 'teamChallenge',
    projectTitre: 'Team Challenge',
    openProject: true,
    openGit: false,
    openVideo: true,
    imageNameList: 'img1l.webp',
    commercial: true,
  },
  {
    imageName: 'img2.webp', //diamondCollection
    descriptions: 'HTML|CSS|Javascript|Local storage for Basket|GitHub',
    linkGit: 'https://github.com/TinaSemashko/ProjetJavascriptAssofac',
    linkProject: 'https://loquacious-empanada-12b1c9.netlify.app/',
    linkVideo: '',
    src: '',
    degY: 0,
    alt: 'Site e-commerce pour la société de bijoux (projet de formation)',
    projectName: 'diamondCollection',
    projectTitre: 'Diamond Collection',
    openProject: true,
    openGit: true,
    openVideo: false,
    imageNameList: 'img2l.webp',
    commercial: false,
  },
  {
    imageName: 'img3.webp', //portfolio
    descriptions: 'React|Styled-components|Typescript|Mui-material|GitHub',
    linkGit: 'https://github.com/TinaSemashko/portfolio-clients',
    linkProject: 'https://creation-de-sites-web.netlify.app/',
    linkVideo: '',
    src: '',
    degY: 0,
    alt: 'Portfolio pour les clients',
    projectName: 'portfolio',
    projectTitre: 'Portfolio clients',
    openProject: true,
    openGit: false,
    openVideo: false,
    imageNameList: 'img3l.webp',
    commercial: true,
  },
  {
    imageName: 'img4.webp', //ekea
    descriptions: 'HTML|CSS|Javascript|Bootstrap|JSON|Local storage for Basket|GitHub',
    linkGit: 'https://github.com/Kaiju971/PROJET-NIVEAU-II',
    linkProject: 'https://magical-cocada-6863e7.netlify.app/',
    linkVideo: '',
    src: '',
    degY: 0,
    alt: 'Site e-commerce pour une entreprise de meuble (projet de formation)',
    projectName: 'ekea',
    projectTitre: 'E-kea',
    openProject: true,
    openGit: true,
    openVideo: false,
    imageNameList: 'img4l.webp',
    commercial: false,
  },
  {
    imageName: 'img5.webp', //casinoGame
    descriptions: 'HTML|CSS|Javascript|Bootstrap|GitHub',
    linkGit: 'https://github.com/TinaSemashko/AssofacCasinoGame',
    linkProject: 'https://aquamarine-gnome-52ee5d.netlify.app/',
    linkVideo: '',
    src: '',
    degY: 0,
    alt: 'Jeu de dés',
    projectName: 'casinoGame',
    projectTitre: 'Casino Game',
    openProject: true,
    openGit: true,
    openVideo: false,
    imageNameList: 'img5l.webp',
    commercial: false,
  },
  {
    imageName: 'img6.webp', //garage
    descriptions: 'React|Styled-components|Typecript|Mui-material|PostgreSQL|GitHub|CRUD',
    linkGit: 'https://github.com/TinaSemashko/garage',
    linkProject: 'https://www.tina-space.fr',
    linkVideo: 'Garage',
    src: '',
    degY: 0,
    alt: 'Site e-commerce pour une entreprise de voitures (projet de formation)',
    projectName: 'garage',
    projectTitre: 'Garage',
    openProject: false,
    openGit: true,
    openVideo: false,
    imageNameList: 'img6l.webp',
    commercial: false,
  },

  {
    imageName: 'img8.webp', //weather_react
    descriptions: 'HTML|CSS|React|Bootstrap|API|GitHub',
    linkGit: 'https://github.com/TinaSemashko/weather_react',
    linkProject: 'https://stately-sopapillas-d6d214.netlify.app/',
    linkVideo: '',
    src: '',
    degY: 0,
    alt: 'Une application qui utilise une API pour afficher les prévisions météo d/une ville sélectionnée',
    projectName: 'weatherReact',
    projectTitre: 'Weather',
    openProject: true,
    openGit: true,
    openVideo: false,
    imageNameList: 'img8l.webp',
    commercial: false,
  },

  {
    imageName: 'img10.webp', //connectify
    descriptions: 'React|Styled-components|Typecript|Mui-material|PostgreSQL|GitHub|CRUD',
    linkGit: 'https://github.com/TinaSemashko/connectify-plus',
    linkProject: '',
    linkVideo: 'VideoConnectify',
    src: '',
    degY: 0,
    alt: 'projet de formation',
    projectName: 'connectify',
    projectTitre: 'Connectify',
    openProject: false,
    openGit: true,
    openVideo: false,
    imageNameList: 'img10l.webp',
    commercial: false,
  },
  {
    imageName: 'img11.webp', //assoFacTory
    descriptions: 'React|Styled-components|Javascript|Mui-material|PostgreSQL|GitHub|Work in the team|CRUD',
    linkGit: 'https://github.com/TinaSemashko/AssoFacTorySQL',
    linkProject: '',
    linkVideo: 'VideoAssofactory',
    src: '',
    degY: 0,
    alt: 'un blog (projet de formation)',
    projectName: 'assoFacTory',
    projectTitre: 'AssoFacTory',
    openProject: false,
    openGit: true,
    openVideo: true,
    imageNameList: 'img11l.webp',
    commercial: false,
  },
  {
    imageName: 'img9.webp', //Nastya
    descriptions: 'React|Styled-components|Typescript|Mui-material|GitHub',
    linkGit: '',
    linkProject: 'https://photo-nastya-demchuk.netlify.app/',
    linkVideo: '',
    src: '',
    degY: 0,
    alt: 'Site-vitrine pour une photographe',
    projectName: 'nastyaPhoto',
    projectTitre: 'Photo landing',
    openProject: true,
    openGit: false,
    openVideo: false,
    imageNameList: 'img9l.webp',
    commercial: true,
  },
  {
    imageName: 'img7.webp', //Karamon video
    descriptions: 'React|Styled-components|Typescript|Mui-material|GitHub',
    linkGit: 'private',
    linkProject: 'https://karamon-video.netlify.app/',
    linkVideo: '',
    src: '',
    degY: 0,
    alt: 'Site-vitrine pour un ingénieur vidéo',
    projectName: 'karamonVideo',
    projectTitre: 'Video landing',
    openProject: true,
    openGit: false,
    openVideo: false,
    imageNameList: 'img7l.webp',
    commercial: true,
  },
  {
    imageName: 'img12.webp', //ABS
    descriptions: 'React|Styled-components|Typecript|Mui-material|PostgreSQL|GitHub|Work in the team|CRUD',
    linkGit: 'private',
    linkProject: 'https://www.abs-couverture.fr',
    linkVideo: 'VideoABS',
    src: '',
    degY: 0,
    alt: 'Site Web e-commerse pour une entreprise de construction avec base de données, page d/administration et stockage de photos sur un service tiers',
    projectName: 'ABS',
    projectTitre: 'ABS-couverture',
    openProject: true,
    openGit: false,
    openVideo: true,
    imageNameList: 'img12l.webp',
    commercial: true,
  },
  {
    imageName: 'img13.webp', //Kaya-yoga
    descriptions: 'React|Styled-components|Typecript|Mui-material|PostgreSQL|GitHub|Turborepo',
    linkGit: 'private',
    linkProject: 'https://kaya-yoga.netlify.app/',
    linkVideo: '',
    src: '',
    degY: 0,
    alt: 'Template of site',
    projectName: 'kayayoga',
    projectTitre: 'Kaya-yoga',
    openProject: true,
    openGit: false,
    openVideo: false,
    imageNameList: 'img13l.webp',
    commercial: true,
  },
];
