import { Carousel3d } from '../../types/projects';

export const imagesCarousel: Carousel3d[] = [
  {
    imageName: 'img1.webp', //teamchallenge
    descriptions: 'React|Styled-components|Typecript|Mui-material|PostgreSQL|GitHub|Work in the team',
    linkGit: 'private',
    linkProject: 'https://teamchallenge.io/',
    linkVideo: 'https://youtu.be/b_6AnXj5OxM',
    src: require('../../images/img1.webp'),
    degY: 0,
    alt: 'Plateforme Web pour les juniors, qui rassemble une équipe interfonctionnelle pour son premier projet',
    projectName: 'teamChallenge',
    projectTitre: 'Team Challenge',
    openProject: true,
    openGit: false,
    openVideo: true,
    imageNameList: 'img1l.webp',
    srcList: require('../../images/img1l.webp'),
    category: 'commercial',
  },
  {
    imageName: 'img3.webp', //portfolio
    descriptions: 'React|Styled-components|Typescript|Mui-material|GitHub',
    linkGit: 'https://github.com/TinaSemashko/portfolio-clients',
    linkProject: 'https://creation-de-sites-web.netlify.app/',
    linkVideo: '',
    src: require('../../images/img3.webp'),
    degY: 0,
    alt: 'Portfolio pour les clients',
    projectName: 'portfolio',
    projectTitre: 'Portfolio clients',
    openProject: true,
    openGit: false,
    openVideo: false,
    imageNameList: 'img3l.webp',
    srcList: require('../../images/img3l.webp'),
    category: 'commercial',
  },
  {
    imageName: 'img5.webp', //casinoGame
    descriptions: 'HTML|CSS|Javascript|Bootstrap|GitHub',
    linkGit: 'https://github.com/TinaSemashko/AssofacCasinoGame',
    linkProject: 'https://aquamarine-gnome-52ee5d.netlify.app/',
    linkVideo: '',
    src: require('../../images/img5.webp'),
    degY: 0,
    alt: 'Jeu de dés',
    projectName: 'casinoGame',
    projectTitre: 'Casino Game',
    openProject: true,
    openGit: true,
    openVideo: false,
    imageNameList: 'img5l.webp',
    srcList: require('../../images/img5l.webp'),
    category: 'educational',
  },
  {
    imageName: 'img8.webp', //weather_react
    descriptions: 'HTML|CSS|React|Bootstrap|API|GitHub',
    linkGit: 'https://github.com/TinaSemashko/weather_react',
    linkProject: 'https://stately-sopapillas-d6d214.netlify.app/',
    linkVideo: '',
    src: require('../../images/img8.webp'),
    degY: 0,
    alt: 'Une application qui utilise une API pour afficher les prévisions météo d/une ville sélectionnée',
    projectName: 'weatherReact',
    projectTitre: 'Weather',
    openProject: true,
    openGit: true,
    openVideo: false,
    imageNameList: 'img8l.webp',
    srcList: require('../../images/img8l.webp'),
    category: 'educational',
  },

  {
    imageName: 'img9.webp', //Nastya
    descriptions: 'React|Styled-components|Typescript|Mui-material|GitHub',
    linkGit: '',
    linkProject: 'https://photo-nastya-demchuk.netlify.app/',
    linkVideo: '',
    src: require('../../images/img9.webp'),
    degY: 0,
    alt: 'Site-vitrine pour une photographe',
    projectName: 'nastyaPhoto',
    projectTitre: 'Photo landing',
    openProject: true,
    openGit: false,
    openVideo: false,
    imageNameList: 'img9l.webp',
    srcList: require('../../images/img9l.webp'),
    category: 'commercial',
  },
  {
    imageName: 'img7.webp', //Karamon video
    descriptions: 'React|Styled-components|Typescript|Mui-material|GitHub',
    linkGit: 'private',
    linkProject: 'https://karamon-video.netlify.app/',
    linkVideo: '',
    src: require('../../images/img7.webp'),
    degY: 0,
    alt: 'Site-vitrine pour un ingénieur vidéo',
    projectName: 'karamonVideo',
    projectTitre: 'Video landing',
    openProject: true,
    openGit: false,
    openVideo: false,
    imageNameList: 'img7l.webp',
    srcList: require('../../images/img7l.webp'),
    category: 'commercial',
  },
  {
    imageName: 'img12.webp', //ABS
    descriptions: 'React|Styled-components|Typecript|Mui-material|PostgreSQL|GitHub|Work in the team|CRUD',
    linkGit: 'private',
    linkProject: 'https://www.abs-couverture.fr',
    linkVideo: '',
    src: require('../../images/img12.webp'),
    degY: 0,
    alt: 'Site Web e-commerse pour une entreprise de construction avec base de données, page d/administration et stockage de photos sur un service tiers',
    projectName: 'ABS',
    projectTitre: 'ABS-couverture',
    openProject: true,
    openGit: false,
    openVideo: false,
    imageNameList: 'img12l.webp',
    srcList: require('../../images/img12l.webp'),
    category: 'commercial',
  },
  {
    imageName: 'img13.webp', //Kaya-yoga
    descriptions: 'React|Styled-components|Typecript|Mui-material|PostgreSQL|GitHub|Turborepo',
    linkGit: 'private',
    linkProject: 'https://kaya-yoga.netlify.app/',
    linkVideo: '',
    src: require('../../images/img13.webp'),
    degY: 0,
    alt: 'Template of site',
    projectName: 'kayayoga',
    projectTitre: 'Kaya-yoga',
    openProject: true,
    openGit: false,
    openVideo: false,
    imageNameList: 'img13l.webp',
    srcList: require('../../images/img13l.webp'),
    category: 'commercial',
  },

  // TODO: replace src/srcList with real cover screenshots when ready
  {
    imageName: 'mcpServer.webp',
    descriptions: 'Python|FastMCP|MCP protocol|OAuth2',
    linkGit: '',
    linkProject: '',
    linkVideo: '',
    src: require('../../images/img1.webp'),
    degY: 0,
    alt: 'Serveur MCP unifié pour intégrations de systèmes de gestion hôtelière',
    projectName: 'mcpServer',
    projectTitre: 'MCP Server',
    openProject: false,
    openGit: false,
    openVideo: false,
    imageNameList: 'mcpServerl.webp',
    srcList: require('../../images/img1.webp'),
    category: 'architectural',
    role: 'Architecte technique',
  },
  {
    imageName: 'pmsGateway.webp',
    descriptions: 'Python|FastAPI|MCP|OAuth2|PMS integrations',
    linkGit: '',
    linkProject: '',
    linkVideo: '',
    src: require('../../images/img1.webp'),
    degY: 0,
    alt: 'API gateway centralisant les intégrations PMS via architecture MCP',
    projectName: 'pmsGateway',
    projectTitre: 'PMS Gateway API',
    openProject: false,
    openGit: false,
    openVideo: false,
    imageNameList: 'pmsGatewayl.webp',
    srcList: require('../../images/img1.webp'),
    category: 'architectural',
    role: 'Architecte technique',
  },
  {
    imageName: 'n8nWorkflows.webp',
    descriptions: 'n8n|AI agents|LLM|Webhooks|Databases|Automation',
    linkGit: '',
    linkProject: '',
    linkVideo: '',
    src: require('../../images/img1.webp'),
    degY: 0,
    alt: 'Workflows d\'automatisation avec agents IA — orchestration de processus métiers',
    projectName: 'n8nWorkflows',
    projectTitre: 'n8n Workflows',
    openProject: false,
    openGit: false,
    openVideo: false,
    imageNameList: 'n8nWorkflowsl.webp',
    srcList: require('../../images/img1.webp'),
    category: 'architectural',
    role: 'Architecte technique',
  },
  {
    imageName: 'lucioleQuest.webp',
    descriptions: 'React Native|TypeScript|Expo|Supabase|PostgreSQL|Mistral AI|Edge Functions',
    linkGit: '',
    linkProject: '',
    linkVideo: '',
    src: require('../../images/img1.webp'),
    degY: 0,
    alt: 'Application mobile de chasses au trésor familiales avec énigmes générées par IA',
    projectName: 'lucioleQuest',
    projectTitre: 'Luciole Quest',
    openProject: false,
    openGit: false,
    openVideo: false,
    imageNameList: 'lucioleQuestl.webp',
    srcList: require('../../images/img1.webp'),
    category: 'architectural',
    role: 'Architecte technique',
  },
  {
    imageName: 'alexartia.webp',
    descriptions: 'React|Next.js|TypeScript',
    linkGit: '',
    linkProject: 'https://alexartia.vercel.app/',
    linkVideo: '',
    src: require('../../images/img1.webp'),
    degY: 0,
    alt: 'Service de création et d\'impression de livres uniques pour enfants générés par IA',
    projectName: 'alexartia',
    projectTitre: 'Alexartia',
    openProject: true,
    openGit: false,
    openVideo: false,
    imageNameList: 'alexartial.webp',
    srcList: require('../../images/img1.webp'),
    category: 'architectural',
    role: 'Architecte technique',
  },
  {
    imageName: 'nativaLumi.webp',
    descriptions: 'React|TypeScript', // TODO: confirm full stack
    linkGit: '',
    linkProject: 'https://nativa-lumi.vercel.app/',
    linkVideo: '',
    src: require('../../images/img1.webp'),
    degY: 0,
    alt: 'Site-vitrine pour une masseuse',
    projectName: 'nativaLumi',
    projectTitre: 'Nativa Lumi',
    openProject: true,
    openGit: false,
    openVideo: false,
    imageNameList: 'nativaLumil.webp',
    srcList: require('../../images/img1.webp'),
    category: 'architectural',
    role: 'Architecte technique',
  },
];
